server:
  port: 8001

spring:
  application:
    name: EAM-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/employee/**, /attendance/**, /department/**, /empDept/**
            
        - id: LOGIN-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/login/**
      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          - AddResponseHeader=Access-Control-Allow-Origin, *            
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST